#!/usr/bin/env bash

# Console colors
red='\033[0;91m'
red_bg='\033[101m'
yellow_bg='\033[43;90m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

LARAVEL_ROOT=${PWD##*/}

# ---------- Runtime ------------

if [ -d "$PROJECT_ROOT/$LARAVEL_ROOT" ]; then
  echo -e "${yellow}Directory exists${NC}: $PROJECT_ROOT/$LARAVEL_ROOT"
  echo "Delete this directory and start Laravel installation?"
  echo "Press Enter to delete it and continue or Ctrl-C to cancel..."
  read -p ""
fi

rm -r "$PROJECT_ROOT/$LARAVEL_ROOT" 2>/dev/null

# Reset containers
fin reset -f

# Require installer
fin exec composer global require "laravel/installer"

# Install laravel
cd "$PROJECT_ROOT"
fin exec composer create-project --prefer-dist laravel/laravel "$LARAVEL_ROOT"

echo "Copying Database settings..."
fin exec sed -i 's/DB_HOST=127.0.0.1/DB_HOST=db/g' "${LARAVEL_ROOT}/.env"
fin exec sed -i 's/DB_DATABASE=laravel/DB_DATABASE=default/g' "${LARAVEL_ROOT}/.env"
fin exec sed -i 's/DB_USERNAME=root/DB_USERNAME=user/g' "${LARAVEL_ROOT}/.env"
fin exec sed -i 's/DB_PASSWORD=/DB_PASSWORD=user/g' "${LARAVEL_ROOT}/.env"

echo "Installing artisan addon..."
fin addon install artisan

# This code resolve PHP Composer create-project issue copying all needed files.
# Ref.: https://github.com/composer/composer/issues/7455
cd $PROJECT_ROOT
cp -R .docksal $LARAVEL_ROOT
cp -R .github $LARAVEL_ROOT
cp README.md $LARAVEL_ROOT/COATI.md
cd ..
mv $LARAVEL_ROOT $LARAVEL_ROOT-Old
cd $LARAVEL_ROOT-Old
mv $LARAVEL_ROOT ..
cd ..
sudo rm -R $LARAVEL_ROOT-Old #needs sudo password

echo "------------------------------------"
echo -e "${green}Installation complete.${NC}"
echo -e "  URL: ${yellow}http://$VIRTUAL_HOST${NC}"
