#!/usr/bin/env bash

# Console colors
red='\033[0;91m'
red_bg='\033[101m'
yellow_bg='\033[43;90m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

LARAVEL_ROOT="./"

# ---------- Runtime ------------

if [ ! $(ls -A "$PROJECT_ROOT" | wc -l) -eq 3 ]; then
  echo -e "${yellow}Directory is not empty${NC}: $PROJECT_ROOT"
  echo "Are you sure to want use this directory and start Laravel installation?"
  echo "Press Enter to delete it and continue or Ctrl-C to cancel..."
  read -p ""
fi

# Reset containers
fin reset -f

# Require installer
fin exec composer global require "laravel/installer"

# Install laravel
cd "$PROJECT_ROOT"
fin exec composer create-project --prefer-dist laravel/laravel "$LARAVEL_ROOT"

echo "Copying Database settings..."
fin exec sed -i 's/DB_HOST=127.0.0.1/DB_HOST=db/g' ".env"
fin exec sed -i 's/DB_DATABASE=laravel/DB_DATABASE=default/g' ".env"
fin exec sed -i 's/DB_USERNAME=root/DB_USERNAME=user/g' ".env"
fin exec sed -i 's/DB_PASSWORD=/DB_PASSWORD=user/g' ".env"

echo "Installing artisan addon..."
fin addon install artisan

echo "------------------------------------"
echo -e "${green}Installation complete.${NC}"
echo -e "  URL: ${yellow}http://$VIRTUAL_HOST${NC}"
