#!/usr/bin/env bash

## Run Laravel Artisan Commands
##
## Artisan is the command-line interface included with Laravel.
## It provides a number of helpful commands that can assist you while you build your application.
## To view a list of all available Artisan commands, you may use the list command:
##   fin artisan list
##
## Usage:
##   artisan [args]     Run artisan see https://laravel.com/docs/master/artisan

# run the command in the container.
cd "$(dirname "$PROJECT_ROOT/$DOCROOT")"
fin exec php artisan "$@"

# install all the Laravel Packages required by the project
fin exec composer require laravel/breeze barryvdh/laravel-debugbar --dev
fin exec composer require nwidart/laravel-modules spatie/laravel-permission livewire/livewire
fin exec php artisan breeze:install
#fin exec php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider"
#fin exec php artisan vendor:publish --provider="Barryvdh\Debugbar\ServiceProvider"
